// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP7uwSOlyRrsOFH0eVCZ-FO8mYrKMYB5Q',
    appId: '1:610338153490:web:61a8ee464cb74307d5e4cb',
    messagingSenderId: '610338153490',
    projectId: 'alimentos-d0d51',
    authDomain: 'alimentos-d0d51.firebaseapp.com',
    storageBucket: 'alimentos-d0d51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAym00J8rBvaFSjGgoVRP4cM-P614Gk1Y',
    appId: '1:610338153490:android:b5c541d41478d528d5e4cb',
    messagingSenderId: '610338153490',
    projectId: 'alimentos-d0d51',
    storageBucket: 'alimentos-d0d51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI2SM4lsOuqHXvbddHtk2_lTox3Bi4jKU',
    appId: '1:610338153490:ios:e0909a48eae65336d5e4cb',
    messagingSenderId: '610338153490',
    projectId: 'alimentos-d0d51',
    storageBucket: 'alimentos-d0d51.firebasestorage.app',
    iosBundleId: 'com.example.alimentos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI2SM4lsOuqHXvbddHtk2_lTox3Bi4jKU',
    appId: '1:610338153490:ios:e0909a48eae65336d5e4cb',
    messagingSenderId: '610338153490',
    projectId: 'alimentos-d0d51',
    storageBucket: 'alimentos-d0d51.firebasestorage.app',
    iosBundleId: 'com.example.alimentos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP7uwSOlyRrsOFH0eVCZ-FO8mYrKMYB5Q',
    appId: '1:610338153490:web:3c9aab828ff9e05ed5e4cb',
    messagingSenderId: '610338153490',
    projectId: 'alimentos-d0d51',
    authDomain: 'alimentos-d0d51.firebaseapp.com',
    storageBucket: 'alimentos-d0d51.firebasestorage.app',
  );
}
